version: "3.8"

services:
  db:
    container_name: "workoutDB"
    image: postgres:17-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
